#!/bin/bash


read -p "Are you sure you want to uninstall? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
# files
    rm -f "${HOME}/.zshrc"
    rm -f "${HOME}/.p10k.zsh"
    rm -f "${HOME}/.config/Code/Usersettings.json"
    rm -f "${HOME}/.config/Code - OSS/Usersettings.json"
    rm -f "${HOME}/.config/code-flags.conf"
    rm -f "${HOME}/.config/spotify-flags.conf"
    rm -f "${HOME}/.config/dunst/dunst"
    rm -f "${HOME}/.config/fish/fish"
    rm -f "${HOME}/.config/hydewall/bash/hyprland"
    rm -f "${HOME}/.config/hypranimations.conf"
    rm -f "${HOME}/.config/hyprhyprland.conf"
    rm -f "${HOME}/.config/hyprwindowrules.conf"
    rm -f "${HOME}/.config/hyprthemeshyprland"
    rm -f "${HOME}/.config/hyprkeybindings.conf"
    rm -f "${HOME}/.config/hyprmonitors.conf"
    rm -f "${HOME}/.config/hypruserprefs.conf"
    rm -f "${HOME}/.config/hyprnvidia.conf"
    rm -f "${HOME}/.local/share/bin/hyprland"
    rm -f "${HOME}/.config/kitty/kitty"
    rm -f "${HOME}/.config/Kvantum/kvantum"
    rm -f "${HOME}/.config/lsd/lsd"
    rm -f "${HOME}/.config/MangoHud/mangohud"
    rm -f "${HOME}/.config/neofetch/neofetch"
    rm -f "${HOME}/.config/qt5ct/qt5ct"
    rm -f "${HOME}/.config/qt6ct/qt6ct"
    rm -f "${HOME}/.config/rofi/rofi"
    rm -f "${HOME}/.config/swaylock/swaylock-effects"
    rm -f "${HOME}/.config/waybar/modules/waybar"
    rm -f "${HOME}/.config/waybar/config.jsonc"
    rm -f "${HOME}/.config/waybar/style.css"
    rm -f "${HOME}/.config/waybar/theme.css"
    rm -f "${HOME}/.config/waybar/config.ctl"
    rm -f "${HOME}/.config/wlogout/wlogout"
    rm -f "${HOME}/.config/xsettingsd/nwg-look"
    rm -f "${HOME}/.config/nwg-look/nwg-look"
    rm -f "${HOME}/.config/gtk-3.0/nwg-look"
    rm -f "${HOME}/.icons/default/nwg-look"
    rm -f "${HOME}/.gtkrc-2.0/nwg-look"
    rm -f "${HOME}/.config/dolphinrc"
    rm -f "${HOME}/.config/kdeglobals"
    rm -f "${HOME}/.local/share/dolphin/dolphin"
    rm -f "${HOME}/.local/share/kxmlgui5/dolphin/dolphin"
    rm -f "${HOME}/.local/share/kio/servicemenus/hydewallpaper.desktop"
    rm -f "${HOME}/.config/libinput-gestures.conf"

    # direcotries
    rm -rf "${HOME}/.config/Code"
    rm -rf "${HOME}/.config/Code - OSS"
    rm -rf "${HOME}/.config/dunst"
    rm -rf "${HOME}/.config/fish"
    rm -rf "${HOME}/.config/hydewall"
    rm -rf "${HOME}/.config/hyprland"
    rm -rf "${HOME}/.config/kitty"
    rm -rf "${HOME}/.config/Kvantum"
    rm -rf "${HOME}/.config/lsd"
    rm -rf "${HOME}/.config/MangoHud"
    rm -rf "${HOME}/.config/neofetch"
    rm -rf "${HOME}/.config/qt5ct"
    rm -rf "${HOME}/.config/qt6ct"
    rm -rf "${HOME}/.config/rofi"
    rm -rf "${HOME}/.config/swaylock"
    rm -rf "${HOME}/.config/waybar"
    rm -rf "${HOME}/.config/wlogout"
    rm -rf "${HOME}/.config/xsettingsd"
    rm -rf "${HOME}/.config/nwg-look"
    rm -rf "${HOME}/.config/gtk-3.0"
    rm -rf "${HOME}/.icons/default"
    rm -rf "${HOME}/.config/dolphin"
    rm -rf "${HOME}/.local/share/dolphin"

echo "Uninstallation completed."

else 
    echo "Uninstallation aborted."
fi